version: "3.8"

services:
  postgres_db:
    container_name: dev_postgres_db
    image: postgres:latest
    env_file:
      - .env.db
    ports:
        - "5432:5432"
    restart: always
    networks:
      - chi_server

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    logging:
      driver: none
    networks:
      - chi_server

  server:
    container_name: dev_server
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "5200:5200"
    depends_on:
      - postgres_db
    links:
      - postgres_db:postgres_db
    volumes:
      - .:/app
    restart: always
    networks:
      - chi_server

networks:
  chi_server:
    driver: bridge